services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:5000 --reload run:app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - panamaster-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=panamaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - panamaster-network

volumes:
  postgres_data:

networks:
  panamaster-network:
    driver: bridge 