name: 🚀 Deploy to Panamaster Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 90.156.135.41 >> ~/.ssh/known_hosts

    - name: Deploy via rsync
      run: |
        rsync -az --delete --exclude=".git*" ./ root@90.156.135.41:/srv/panamaster/
