name: Deploy Panamaster

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 bandit safety

    - name: Run tests
      run: |
        pytest --cov=app tests/

    - name: Lint code (flake8)
      run: |
        flake8 app tests || true

    - name: Bandit security check
      run: |
        bandit -r app || true

    - name: Safety check for known vulnerable packages
      run: |
        safety check || true

    - name: Deploy via rsync
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 90.156.135.41 >> ~/.ssh/known_hosts
        rsync -az --delete --exclude=".git*" ./ root@90.156.135.41:/srv/panamaster/
